In [3]:
import math

# Print the value of pi
print ('pi = ', math.pi)

# Print the value of e
print ('e = ', math.e)

# Print the value of square root of 2
print ('sqrt(2) = ', math.sqrt(2))

pi =  3.141592653589793
e =  2.718281828459045
sqrt(2) =  1.4142135623730951


In [8]:
from mpmath import mp

mp.dps = 1000 + 1

print('print 1000 digits of pi behind decimal point')
print(mp.pi)

print('print 1000 digits of e behind decimal point')
print(mp.e)

print('print 1000 digits of sqrt(2) behind decimal point')
print(mp.sqrt(2))

print 1000 digits of pi behind decimal point
3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593344612847564823378678316527120190914564856692346034861045432664821339360726024914127372458700660631558817488152092096282925409171536436789259036001133053054882046652138414695194151160943305727036575959195309218611738193261179310511854807446237996274956735188575272489122793818301194912983367336244065664308602139494639522473719070217986094370277053921717629317675238467481846766940513200056812714526356082778577134275778960917363717872146844090122495343014654958537105079227968925892354201995611212902196086403441815981362977477130996051870721134999999837297804995105973173281609631859502445945534690830264252230825334468503526193118817101000313783875288658753320838142061717766914730359825349042875546873115956286388235378759375195778185

In [13]:
import numpy

# 一行三列的向量
m_1_x_3 = numpy.array([[1,2,3]])
print(m_1_x_3)
# T 表示向量的转置
print(m_1_x_3.T)

# 三行一列的向量
m_3_x_1 = numpy.array([[1], [2], [3]])
print(m_3_x_1)

[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [20]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

A_first_col = A[:,0] # saved as one dimension row
print(A_first_col)

A_first_col_V2 = A[:,[0]] # saved as a column
print(A_first_col_V2)

A_first_second_col_V2 = A[:,[0,1]] # extract first and second columns
print(A_first_second_col_V2)

A_first_third_col_V2 = A[:,[0,2]] # extract first and third columns
print(A_first_third_col_V2)

A_first_row = A[[0],:] # extract first row
print(A_first_row)

A_second_row = A[[1],:] # extract second row
print(A_second_row)

A_second_row_first_col = A[[1],[0]] # i = 2, j = 1
print(A_second_row_first_col)


[1 4]
[[1]
 [4]]
[[1 2]
 [4 5]]
[[1 3]
 [4 6]]
[[1 2 3]]
[[4 5 6]]
[4]
